"""update_agent_fields_for_representative

Revision ID: 142a80df8daf
Revises: 6e6ab35a5ca6
Create Date: 2026-01-19 00:56:20.021518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142a80df8daf'
down_revision: Union[str, None] = '6e6ab35a5ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Adicionar novas colunas
    op.add_column('agents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('personality', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('communication_style', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('knowledge_base', sa.Text(), nullable=True))
    
    # Migrar dados de system_prompt para personality
    op.execute("UPDATE agents SET personality = system_prompt WHERE system_prompt IS NOT NULL")
    op.execute("UPDATE agents SET personality = 'Profissional e cordial' WHERE personality IS NULL")
    
    # Tornar personality NOT NULL
    op.alter_column('agents', 'personality', nullable=False)
    
    # Remover coluna antiga
    op.drop_column('agents', 'system_prompt')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('agents', 'knowledge_base')
    op.drop_column('agents', 'communication_style')
    op.drop_column('agents', 'personality')
    op.drop_column('agents', 'description')
    # ### end Alembic commands ###
