"""add_is_active_to_agent

Revision ID: 6e6ab35a5ca6
Revises: d26048876920
Create Date: 2026-01-19 00:49:24.401128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6ab35a5ca6'
down_revision: Union[str, None] = 'd26048876920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Adicionar coluna com valor padrão True para registros existentes
    op.add_column('agents', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE agents SET is_active = TRUE WHERE is_active IS NULL")
    op.alter_column('agents', 'is_active', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'is_active')
    # ### end Alembic commands ###
